### ISSUE TITLE
Set Theory Supplemental Material: How to Prove Two Sets Are Equal (Improper Word Use)

### ISSUE THREAD

**Issue by Anth0ny-A** [Joe-McCann/cs-241-hugo-notes#10]
In the first example of this section, while explaining your proof, you used "compliment" instead of "complement" which is the correct term in context
![Error2](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147458654/0a843f38-4d7c-463b-b1c1-1659a1ec20cf)

**Comment by Joe-McCann** [comment]
Fixed
