### ISSUE TITLE
Set Theory Supplemental Material: How to Prove Two Sets Are Equal (Punctuation Error)

### ISSUE THREAD

**Issue by Anth0ny-A** [Joe-McCann/cs-241-hugo-notes#11]
In the first example of this section, at the end of your proof you wrote "Q.E.D.." instead of "Q.E.D." Extra periods are not needed after an abbreviation.
![Error3](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147458654/37e10f42-9114-46d6-a9d5-17ddd816f956)

**Comment by Joe-McCann** [comment]
Huh, didn't know that, also I fixed it
