### ISSUE TITLE
Set Theory Supplemental Material: How to Prove Two Sets Are Equal (LaTeX Formatting Error)

### ISSUE THREAD

**Issue by Anth0ny-A** [Joe-McCann/cs-241-hugo-notes#12]
At the end of the section, it seems as though you meant to write $P(A ∩ B)=P(A) ∩ P(B)$ in LaTeX but it displayed as plaintext
![Error4](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147458654/cdec8648-4ead-4a14-9810-799302657b85)

**Comment by Joe-McCann** [comment]
Fixed
