### ISSUE TITLE
Set Theory: Equivalence Classes (Spelling Error)

### ISSUE THREAD

**Issue by Anth0ny-A** [Joe-McCann/cs-241-hugo-notes#13]
In this section, after the first definition, you wrote "fundemental" instead of "fundamental"
![Error5](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147458654/d45a1e43-3919-490c-a686-400a9e9f4717)

**Comment by Joe-McCann** [comment]
Fixed
