### ISSUE TITLE
Set Theory: Properties of Relations (Improper Word Use)

### ISSUE THREAD

**Issue by Anth0ny-A** [Joe-McCann/cs-241-hugo-notes#14]
In the second paragraph of this section, you use "Lets" instead of "Let's" which is the correct word in context
![Error6](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147458654/023e1426-7c98-4928-9ad4-32eb40d8d30f)

**Comment by Joe-McCann** [comment]
fixed
