### ISSUE TITLE
Set Theory: Properties of Relations (Improper Word Use)

### ISSUE THREAD

**Issue by Anth0ny-A** [Joe-McCann/cs-241-hugo-notes#15]
In the first definition of the Symmetry subsection, you used "effect" instead of "affect" which is the correct word in context
![Error7](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147458654/92726bdc-def1-40ac-94b9-8f618a56848b)

**Comment by Joe-McCann** [comment]
fixed
