### ISSUE TITLE
Set Theory - Formatting/Spelling Errors

### ISSUE THREAD

**Issue by Bassil-Saleh** [Joe-McCann/cs-241-hugo-notes#8]
On the left menu of the [Set Theory section](https://wjmccann.com/course/settheory/sections/whatisaset/), "supplemental" is misspelled as "supplimental":

![set-theory-supplimental](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/613e5ee5-3ea5-40de-92cf-ad90a71a1c29)

On ["Set Builder Notation"](https://wjmccann.com/course/settheory/sections/buildingsets/), "whose" is misspelled as "whos", and "Lets" is missing an apostrophe:
![set-theory-whos](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/1dcec5cc-5690-43e3-ac09-985a7a09dd7c)

![set-theory-lets](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/bf450485-f641-4e25-9c6e-245efab6e988)

On the example problem for $A\cup B$ in ["Simple Set Operations"](https://wjmccann.com/course/settheory/sections/simplesetoperations/), it looks like you meant to write $A \cup B= \lbrace 1,2,3,4,5,6,7 \rbrace$ in LaTeX, but it came out in plaintext instead:

![set-theory-union](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/5cf2c3b0-8265-49c3-af11-1880d39e184f)

In the definition of $A \cap B$ in ["Simple Set Operations"](https://wjmccann.com/course/settheory/sections/simplesetoperations/), I assume you meant to write $A \cap B$ but used $\cup$ by mistake:

![set-theory-intersection](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/42823173-4ddf-420d-8d09-97ea63b16edb)

In the definition of $A \triangle B$ in ["Simple Set Operations"](https://wjmccann.com/course/settheory/sections/simplesetoperations/), it looks like you meant to write $A\triangle B = (A-B)\cup (B-A) = (A\cup B) - (A\cap B)$ in LaTeX but it came out in plaintext instead:

![set-theory-symmetric-difference](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/146ca76e-63a6-493b-8aa9-8c805e047abf)

On ["Advanced Set Operations"](https://wjmccann.com/course/settheory/sections/advancedsetoperations/), "unique" is misspelled as "unqiue":

![set-theory-unqiue](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/b76649a3-c9c0-4b00-83c6-434efd4e04d9)

In the second footnote of ["Advanced Set Operations"](https://wjmccann.com/course/settheory/sections/advancedsetoperations/), I assume you meant to write "it" instead of "its":

![set-theory-its](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/3c8e8ddd-f455-4fe9-a0bf-5486b5df3e12)

On the Standard Induction Theorem in ["Inductive Method"](https://wjmccann.com/course/settheory/sections/inductivesets/), I assume you meant to write $\lim_{j\rightarrow\infty}A_j = \mathbb{N}$ in LaTeX but it came out in plaintext instead:

![set-theory-standard-induction-theorem](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/f0e4274f-a87e-403f-ad52-2d297b8e267e)

In ["Inductive Method"](https://wjmccann.com/course/settheory/sections/inductivesets/), "Lets" is missing an apostrophe and the LaTeX equation $\lim_{j\rightarrow\infty}A_j = \mathbb{N}$ came out in plaintext:

![set-theory-stronger-induction](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/fffb3198-69d7-4db2-95b0-9b1ff03abce2)

The example problem at the end of ["Inductive Method"](https://wjmccann.com/course/settheory/sections/inductivesets/) also appears to have a LaTeX expression $\lim_{j\rightarrow\infty} A_j=\mathbb{N}$ in plaintext:

![set-theory-inductive-method-example](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/2b835089-1697-49ce-b7ac-fdf5c3bfb59d)

On ["What is a Function?"](https://wjmccann.com/course/settheory/sections/functions/), "according" is misspelled as "accoridng":

![set-theory-accoridng](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/de863202-9a44-4404-8016-c2295e322069)

On ["What is a Function?"](https://wjmccann.com/course/settheory/sections/functions/), "the" is repeated twice as shown in the screenshot below. Did you mean to write "to"?

![set-theory-codomain](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147279084/6a74f56a-f759-413e-a236-9b99f483e822)

**Comment by Joe-McCann** [comment]
Fixed
