### ISSUE TITLE
Set Theory Supplemental Material: How to Prove Two Sets Are Equal (Spelling Error)

### ISSUE THREAD

**Issue by Anth0ny-A** [Joe-McCann/cs-241-hugo-notes#9]
In the first paragraph of this section, "decide" is misspelled as "devide"
![SpellingError1](https://github.com/Joe-McCann/cs-241-hugo-notes/assets/147458654/8110ef9f-301f-4dff-9245-2563565d24ef)

**Comment by Joe-McCann** [comment]
Fixed
